// ALERTS
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const CLEAR_ALERTS = 'CLEAR_ALERTS';

// ERRORS
export const SET_ERRORS = 'SET_ERRORS';

// AUTH
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';
export const USER_LOADED = 'USER_LOADED';
export const USER_LOADING = 'USER_LOADING';
export const AUTH_ERROR = 'AUTH_ERROR';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';
export const SIGN_OUT_USER = 'SIGN_OUT_USER';

// PROFILE
export const PROFILE_LOADED = 'PROFILE_LOADED';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const SET_IS_CURRENT_USER = 'SET_IS_CURRENT_USER';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';

// PROFILES
export const PROFILES_ERROR = 'PROFILES_ERROR';
export const CLEAR_PROFILES = 'CLEAR_PROFILES';
export const PROFILES_LOADED = 'PROFILES_LOADED';
export const MORE_PROFILES_LOADING = 'MORE_PROFILES_LOADING';
export const MORE_PROFILES_LOADED = 'MORE_PROFILES_LOADED';
export const PROFILES_LOADING = 'PROFILES_LOADING';
export const SEARCH_CONSTANTS_LOADED = 'SEARCH_CONSTANTS_LOADED';
